resources:
- manager.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: manager
  newName: scylladb/scylla-manager
  newTag: 2.2.0
- name: operator
  newName: scylladb/scylla-operator
  newTag: v1.0.0

configMapGenerator:
- files:
  - scylla-manager.yaml
  name: manager-config

configurations:
- varconfig.yaml
