
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: webhook-service
        namespace: system
        path: /validate-scylla-scylladb-com-v1alpha1-cluster
    failurePolicy: Fail
    name: vcluster.kb.io
    rules:
      - apiGroups:
          - scylla.scylladb.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusters
